{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "56e81bc8-18c6-475f-8e89-fa45953ed306",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Packages for web scraping\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.common.exceptions import TimeoutException\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import time\n",
    "import random\n",
    "\n",
    "# Packages for the GUI application\n",
    "import tkinter as tk\n",
    "from tkinter import ttk, messagebox\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "579e49ad-d4ac-449c-902d-f994f249bc0b",
   "metadata": {},
   "outputs": [],
   "source": [
    "def setup_driver():\n",
    "    \"\"\"Set up Chrome WebDriver with appropriate options.\"\"\"\n",
    "    chrome_options = Options()\n",
    "    chrome_options.add_argument('--headless=new')\n",
    "    chrome_options.add_argument('--no-sandbox')\n",
    "    chrome_options.add_argument('--disable-dev-shm-usage')\n",
    "    chrome_options.add_argument('--disable-gpu')\n",
    "    chrome_options.add_argument('--window-size=1920x1080')\n",
    "    \n",
    "    # Add user agent\n",
    "    chrome_options.add_argument('--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36')\n",
    "    \n",
    "    # Additional settings to avoid detection\n",
    "    chrome_options.add_experimental_option('excludeSwitches', ['enable-automation'])\n",
    "    chrome_options.add_experimental_option('useAutomationExtension', False)\n",
    "    \n",
    "    # Use ChromeDriverManager to handle driver installation\n",
    "    service = Service(ChromeDriverManager().install())\n",
    "    driver = webdriver.Chrome(service=service, options=chrome_options)\n",
    "    \n",
    "    return driver\n",
    "\n",
    "def get_season_url(year):\n",
    "    \"\"\"Generate URL for a specific Premier League season.\"\"\"\n",
    "    if year == 2024:  # Current season\n",
    "        return \"https://fbref.com/en/comps/9/stats/Premier-League-Stats\"\n",
    "    else:\n",
    "        return f\"https://fbref.com/en/comps/9/{year}-{year+1}/stats/{year}-{year+1}-Premier-League-Stats\"\n",
    "\n",
    "def scrape_season(year):\n",
    "    \"\"\"Scrape data for a specific Premier League season.\"\"\"\n",
    "    url = get_season_url(year)\n",
    "    \n",
    "    try:\n",
    "        # Set up the driver\n",
    "        driver = setup_driver()\n",
    "        \n",
    "        # Load the page\n",
    "        print(\"Loading page...\")\n",
    "        driver.get(url)\n",
    "        \n",
    "        # Wait for the table to load\n",
    "        print(\"Waiting for table to load...\")\n",
    "        wait = WebDriverWait(driver, 20)\n",
    "        wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, 'table#stats_standard')))\n",
    "        \n",
    "        # Get the page source\n",
    "        print(\"Parsing data...\")\n",
    "        soup = BeautifulSoup(driver.page_source, 'html.parser')\n",
    "        \n",
    "        # Find the stats table\n",
    "        stats_table = soup.find('table', {'id': 'stats_standard'})\n",
    "        if not stats_table:\n",
    "            print(\"No stats table found!\")\n",
    "            return None\n",
    "            \n",
    "        # Extract player data\n",
    "        all_players = []\n",
    "        for row in stats_table.find('tbody').find_all('tr'):\n",
    "            try:\n",
    "                # Get player data from the row\n",
    "                player_name = row.find('td', {'data-stat': 'player'}).text.strip()\n",
    "                squad_name = row.find('td', {'data-stat': 'team'}).text.strip()\n",
    "                age = row.find('td', {'data-stat': 'age'}).text.strip()\n",
    "                nation = row.find('td', {'data-stat': 'nationality'}).text.strip() if row.find('td', {'data-stat': 'nationality'}) else ''\n",
    "                \n",
    "                all_players.append({\n",
    "                    'Player': player_name,\n",
    "                    'Squad': squad_name,\n",
    "                    'Age': age,\n",
    "                    'Nationality': nation\n",
    "                })\n",
    "                \n",
    "            except (AttributeError, IndexError) as e:\n",
    "                print(f\"Error parsing row: {str(e)}\")\n",
    "                continue\n",
    "        \n",
    "        # Create DataFrame\n",
    "        df = pd.DataFrame(all_players)\n",
    "        df['Season'] = f'{year}-{year+1}'\n",
    "        \n",
    "        print(f\"Successfully scraped {len(df)} players\")\n",
    "        return df\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"Error: {str(e)}\")\n",
    "        return None\n",
    "        \n",
    "    finally:\n",
    "        driver.quit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "283ebde9-0473-4281-8dca-8bd2b5298a58",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Scraping season 2024-2025...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 567 players\n",
      "Success! Found 567 players\n",
      "\n",
      "Scraping season 2023-2024...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 580 players\n",
      "Success! Found 580 players\n",
      "\n",
      "Scraping season 2022-2023...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 569 players\n",
      "Success! Found 569 players\n",
      "\n",
      "Scraping season 2021-2022...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 546 players\n",
      "Success! Found 546 players\n",
      "\n",
      "Scraping season 2020-2021...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 532 players\n",
      "Success! Found 532 players\n",
      "\n",
      "Scraping season 2019-2020...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 522 players\n",
      "Success! Found 522 players\n",
      "\n",
      "Scraping season 2018-2019...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 508 players\n",
      "Success! Found 508 players\n",
      "\n",
      "Scraping season 2017-2018...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 529 players\n",
      "Success! Found 529 players\n",
      "\n",
      "Scraping season 2016-2017...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 543 players\n",
      "Success! Found 543 players\n",
      "\n",
      "Scraping season 2015-2016...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 561 players\n",
      "Success! Found 561 players\n",
      "\n",
      "Scraping season 2014-2015...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 549 players\n",
      "Success! Found 549 players\n",
      "\n",
      "Scraping season 2013-2014...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 561 players\n",
      "Success! Found 561 players\n",
      "\n",
      "Scraping season 2012-2013...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 537 players\n",
      "Success! Found 537 players\n",
      "\n",
      "Scraping season 2011-2012...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 561 players\n",
      "Success! Found 561 players\n",
      "\n",
      "Scraping season 2010-2011...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 563 players\n",
      "Success! Found 563 players\n",
      "\n",
      "Scraping season 2009-2010...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 565 players\n",
      "Success! Found 565 players\n",
      "\n",
      "Scraping season 2008-2009...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 563 players\n",
      "Success! Found 563 players\n",
      "\n",
      "Scraping season 2007-2008...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 554 players\n",
      "Success! Found 554 players\n",
      "\n",
      "Scraping season 2006-2007...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 551 players\n",
      "Success! Found 551 players\n",
      "\n",
      "Scraping season 2005-2006...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 553 players\n",
      "Success! Found 553 players\n",
      "\n",
      "Scraping season 2004-2005...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 533 players\n",
      "Success! Found 533 players\n",
      "\n",
      "Scraping season 2003-2004...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 530 players\n",
      "Success! Found 530 players\n",
      "\n",
      "Scraping season 2002-2003...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 538 players\n",
      "Success! Found 538 players\n",
      "\n",
      "Scraping season 2001-2002...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 543 players\n",
      "Success! Found 543 players\n",
      "\n",
      "Scraping season 2000-2001...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 559 players\n",
      "Success! Found 559 players\n",
      "\n",
      "Scraping season 1999-2000...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 548 players\n",
      "Success! Found 548 players\n",
      "\n",
      "Scraping season 1998-1999...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 560 players\n",
      "Success! Found 560 players\n",
      "\n",
      "Scraping season 1997-1998...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 550 players\n",
      "Success! Found 550 players\n",
      "\n",
      "Scraping season 1996-1997...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 523 players\n",
      "Success! Found 523 players\n",
      "\n",
      "Scraping season 1995-1996...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 516 players\n",
      "Success! Found 516 players\n",
      "\n",
      "Scraping season 1994-1995...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 554 players\n",
      "Success! Found 554 players\n",
      "\n",
      "Scraping season 1993-1994...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 565 players\n",
      "Success! Found 565 players\n",
      "\n",
      "Scraping season 1992-1993...\n",
      "Loading page...\n",
      "Waiting for table to load...\n",
      "Parsing data...\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Error parsing row: 'NoneType' object has no attribute 'text'\n",
      "Successfully scraped 562 players\n",
      "Success! Found 562 players\n",
      "\n",
      "Total players found across all seasons: 18095\n",
      "\n",
      "Data saved to 'premier_league_players_all_seasons.csv'\n",
      "\n",
      "Sample of data (3 rows per season):\n",
      "                  Player            Squad     Age Nationality     Season\n",
      "0             Max Aarons      Bournemouth  25-112     eng ENG  2024-2025\n",
      "1      Joshua Acheampong          Chelsea  18-356     eng ENG  2024-2025\n",
      "2            Tyler Adams      Bournemouth  26-071      us USA  2024-2025\n",
      "567           Max Aarons      Bournemouth      23     eng ENG  2023-2024\n",
      "568    Joshua Acheampong          Chelsea      17     eng ENG  2023-2024\n",
      "...                  ...              ...     ...         ...        ...\n",
      "16969        Micky Adams      Southampton      31     eng ENG  1993-1994\n",
      "16970         Neil Adams     Norwich City      27     eng ENG  1993-1994\n",
      "17533        Gary Ablett          Everton      26     eng ENG  1992-1993\n",
      "17534        Micky Adams      Southampton      30     eng ENG  1992-1993\n",
      "17535         Neil Adams  Oldham Athletic      26     eng ENG  1992-1993\n",
      "\n",
      "[99 rows x 5 columns]\n"
     ]
    }
   ],
   "source": [
    "# Run the scraper for multiple seasons\n",
    "all_seasons = []\n",
    "\n",
    "# Start with recent seasons first\n",
    "for year in range(2024, 1991, -1):  # From 2023 back to 1992\n",
    "    print(f\"\\nScraping season {year}-{year+1}...\")\n",
    "    df = scrape_season(year)\n",
    "    if df is not None:\n",
    "        all_seasons.append(df)\n",
    "        print(f\"Success! Found {len(df)} players\")\n",
    "    else:\n",
    "        print(f\"Failed to scrape season {year}-{year+1}\")\n",
    "    \n",
    "    # Add a delay between seasons\n",
    "    time.sleep(random.uniform(3, 5))\n",
    "\n",
    "# Combine all seasons\n",
    "if all_seasons:\n",
    "    final_df = pd.concat(all_seasons, ignore_index=True)\n",
    "    print(f\"\\nTotal players found across all seasons: {len(final_df)}\")\n",
    "    \n",
    "    # Save to CSV\n",
    "    final_df.to_csv('premier_league_players_all_seasons.csv', index=False)\n",
    "    print(\"\\nData saved to 'premier_league_players_all_seasons.csv'\")\n",
    "    \n",
    "    # Display sample\n",
    "    print(\"\\nSample of data (3 rows per season):\")\n",
    "    print(final_df.groupby('Season').head(3))\n",
    "else:\n",
    "    print(\"No data was successfully scraped\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b35954f5-1c65-4396-b58c-17a3494af3db",
   "metadata": {},
   "outputs": [],
   "source": [
    "class PLTeamQuiz:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"Premier League Team Connection Quiz\")\n",
    "        self.root.geometry(\"800x600\")\n",
    "        \n",
    "        # Load data\n",
    "        self.load_data()\n",
    "        \n",
    "        # Create GUI elements\n",
    "        self.create_widgets()\n",
    "        \n",
    "    def load_data(self):\n",
    "        data_dir = Path('/Users/julianball/Downloads/FBREF')\n",
    "        dfs = []\n",
    "        \n",
    "        for year in range(1992, 2025):\n",
    "            file_path = data_dir / f'PL{year}.csv'\n",
    "            if file_path.exists():\n",
    "                df = pd.read_csv(file_path)\n",
    "                df['year'] = year\n",
    "                dfs.append(df)\n",
    "        \n",
    "        self.df_combined = pd.concat(dfs, ignore_index=True)\n",
    "        self.df_combined = self.df_combined.drop(columns=[\"Rk\", \"Age\"])\n",
    "        \n",
    "        # Create set of all teams for quick lookup\n",
    "        self.all_teams = sorted(set(self.df_combined['Squad'].unique()))\n",
    "    \n",
    "    def create_widgets(self):\n",
    "        # Main frame\n",
    "        main_frame = ttk.Frame(self.root, padding=\"10\")\n",
    "        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))\n",
    "        \n",
    "        # Title\n",
    "        title = ttk.Label(main_frame, text=\"Premier League Team Connection Quiz\", \n",
    "                         font=('Helvetica', 16, 'bold'))\n",
    "        title.grid(row=0, column=0, columnspan=2, pady=10)\n",
    "        \n",
    "        # Description\n",
    "        desc = ttk.Label(main_frame, text=\"Find players who have played for both selected teams!\",\n",
    "                        wraplength=600)\n",
    "        desc.grid(row=1, column=0, columnspan=2, pady=5)\n",
    "        \n",
    "        # Team 1 selection\n",
    "        ttk.Label(main_frame, text=\"First Team:\").grid(row=2, column=0, pady=5)\n",
    "        self.team1_var = tk.StringVar()\n",
    "        self.team1_combo = ttk.Combobox(main_frame, textvariable=self.team1_var, values=self.all_teams)\n",
    "        self.team1_combo.grid(row=2, column=1, pady=5, sticky=tk.W)\n",
    "        \n",
    "        # Team 2 selection\n",
    "        ttk.Label(main_frame, text=\"Second Team:\").grid(row=3, column=0, pady=5)\n",
    "        self.team2_var = tk.StringVar()\n",
    "        self.team2_combo = ttk.Combobox(main_frame, textvariable=self.team2_var, values=self.all_teams)\n",
    "        self.team2_combo.grid(row=3, column=1, pady=5, sticky=tk.W)\n",
    "        \n",
    "        # Find button\n",
    "        ttk.Button(main_frame, text=\"Find Connections\", \n",
    "                  command=self.find_connections).grid(row=4, column=0, columnspan=2, pady=20)\n",
    "        \n",
    "        # Results area\n",
    "        self.results_text = tk.Text(main_frame, height=5, width=60, wrap=tk.WORD)\n",
    "        self.results_text.grid(row=5, column=0, columnspan=2, pady=10)\n",
    "        \n",
    "        # Guess entry label\n",
    "        self.guess_label = ttk.Label(main_frame, text=\"Enter your guesses (one player per line):\")\n",
    "        self.guess_label.grid(row=6, column=0, columnspan=2, pady=(10,0))\n",
    "        self.guess_label.grid_remove()\n",
    "        \n",
    "        # Guess entry area\n",
    "        self.guess_text = tk.Text(main_frame, height=5, width=60, wrap=tk.WORD)\n",
    "        self.guess_text.grid(row=7, column=0, columnspan=2, pady=5)\n",
    "        self.guess_text.grid_remove()\n",
    "        \n",
    "        # Check answers button\n",
    "        self.check_btn = ttk.Button(main_frame, text=\"Check Answers\", \n",
    "                                  command=self.check_answers)\n",
    "        self.check_btn.grid(row=8, column=0, columnspan=2, pady=5)\n",
    "        self.check_btn.grid_remove()\n",
    "        \n",
    "        # Score display\n",
    "        self.score_label = ttk.Label(main_frame, text=\"\")\n",
    "        self.score_label.grid(row=9, column=0, columnspan=2, pady=5)\n",
    "        self.score_label.grid_remove()\n",
    "        \n",
    "        # Show answer button\n",
    "        self.show_answer_btn = ttk.Button(main_frame, text=\"Give Up - Show Answers\", \n",
    "                                        command=self.toggle_answer)\n",
    "        self.show_answer_btn.grid(row=10, column=0, columnspan=2, pady=10)\n",
    "        self.show_answer_btn.grid_remove()\n",
    "        \n",
    "        # Answer area\n",
    "        self.answer_text = tk.Text(main_frame, height=5, width=60, wrap=tk.WORD)\n",
    "        self.answer_text.grid(row=11, column=0, columnspan=2, pady=10)\n",
    "        self.answer_text.grid_remove()\n",
    "    \n",
    "    def find_players_for_team(self, team):\n",
    "        \"\"\"Find all players who have played for a team.\"\"\"\n",
    "        return set(self.df_combined[self.df_combined['Squad'] == team]['Player'].unique())\n",
    "    \n",
    "    def find_connections(self):\n",
    "        team1 = self.team1_var.get()\n",
    "        team2 = self.team2_var.get()\n",
    "        \n",
    "        if not team1 or not team2:\n",
    "            messagebox.showerror(\"Error\", \"Please select both teams\")\n",
    "            return\n",
    "        \n",
    "        if team1 == team2:\n",
    "            messagebox.showerror(\"Error\", \"Please select different teams\")\n",
    "            return\n",
    "        \n",
    "        # Find players for each team\n",
    "        team1_players = self.find_players_for_team(team1)\n",
    "        team2_players = self.find_players_for_team(team2)\n",
    "        \n",
    "        # Find players who played for both teams\n",
    "        self.common_players = sorted(list(team1_players & team2_players))\n",
    "        \n",
    "        # Display results\n",
    "        self.results_text.delete(1.0, tk.END)\n",
    "        self.results_text.insert(tk.END, f\"Find players who have played for both {team1} and {team2}\\n\")\n",
    "        self.results_text.insert(tk.END, f\"Number of players to find: {len(self.common_players)}\\n\")\n",
    "        \n",
    "        # Show guessing interface\n",
    "        self.guess_label.grid()\n",
    "        self.guess_text.grid()\n",
    "        self.check_btn.grid()\n",
    "        self.score_label.grid()\n",
    "        self.show_answer_btn.grid()\n",
    "        \n",
    "        # Clear previous guesses and answers\n",
    "        self.guess_text.delete(1.0, tk.END)\n",
    "        self.answer_text.delete(1.0, tk.END)\n",
    "        self.answer_text.grid_remove()\n",
    "        self.score_label.configure(text=\"\")\n",
    "        self.show_answer_btn.configure(text=\"Give Up - Show Answers\")\n",
    "    \n",
    "    def check_answers(self):\n",
    "        # Get user guesses\n",
    "        guesses = self.guess_text.get(1.0, tk.END).strip().split('\\n')\n",
    "        guesses = [g.strip() for g in guesses if g.strip()]\n",
    "        \n",
    "        # Convert both lists to sets for comparison\n",
    "        correct_answers = set(self.common_players)\n",
    "        user_guesses = set(guesses)\n",
    "        \n",
    "        # Calculate correct and incorrect guesses\n",
    "        correct_guesses = user_guesses & correct_answers\n",
    "        incorrect_guesses = user_guesses - correct_answers\n",
    "        remaining = correct_answers - user_guesses\n",
    "        \n",
    "        # Update score label\n",
    "        score_text = f\"Correct: {len(correct_guesses)} | \"\n",
    "        score_text += f\"Incorrect: {len(incorrect_guesses)} | \"\n",
    "        score_text += f\"Remaining: {len(remaining)}\"\n",
    "        self.score_label.configure(text=score_text)\n",
    "        \n",
    "        # Highlight correct and incorrect guesses\n",
    "        self.guess_text.tag_remove('correct', '1.0', tk.END)\n",
    "        self.guess_text.tag_remove('incorrect', '1.0', tk.END)\n",
    "        \n",
    "        # Configure tags\n",
    "        self.guess_text.tag_configure('correct', foreground='green')\n",
    "        self.guess_text.tag_configure('incorrect', foreground='red')\n",
    "        \n",
    "        # Apply highlighting\n",
    "        for guess in guesses:\n",
    "            start = '1.0'\n",
    "            while True:\n",
    "                start = self.guess_text.search(guess, start, tk.END)\n",
    "                if not start:\n",
    "                    break\n",
    "                end = f\"{start}+{len(guess)}c\"\n",
    "                tag = 'correct' if guess in correct_guesses else 'incorrect'\n",
    "                self.guess_text.tag_add(tag, start, end)\n",
    "                start = end\n",
    "    \n",
    "    def toggle_answer(self):\n",
    "        if self.answer_text.grid_info():\n",
    "            self.answer_text.grid_remove()\n",
    "            self.show_answer_btn.configure(text=\"Give Up - Show Answers\")\n",
    "        else:\n",
    "            self.answer_text.delete(1.0, tk.END)\n",
    "            self.answer_text.insert(tk.END, \"\\n\".join(sorted(self.common_players)))\n",
    "            self.answer_text.grid()\n",
    "            self.show_answer_btn.configure(text=\"Hide Answers\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    app = PLTeamQuiz(root)\n",
    "    root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4a3f6ff0-02d9-47c2-9444-3c2f6fbee988",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
